/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#2a4968",
        "surface-container-high": "#e9e8eb",
        "secondary-container": "#b1ecd4",
        "primary-fixed-dim": "#abc9ef",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#14503f",
        "surface-container-highest": "#e3e2e5",
        "on-surface-variant": "#43474d",
        "outline": "#73777e",
        "background": "#faf9fc",
        "tertiary-container": "#6f181d",
        "tertiary": "#50000a",
        "on-primary": "#ffffff",
        "surface-variant": "#e3e2e5",
        "on-surface": "#1a1c1e",
        "secondary": "#306856",
        "inverse-primary": "#abc9ef",
        "surface-container": "#eeedf0",
        "on-error-container": "#93000a",
        "surface-bright": "#faf9fc",
        "surface-dim": "#dad9dd",
        "surface-tint": "#436182",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#410006",
        "surface-container-low": "#f4f3f6",
        "on-secondary-container": "#356d5a",
        "on-error": "#ffffff",
        "primary-fixed": "#d1e4ff",
        "secondary-fixed-dim": "#98d3bc",
        "primary": "#002542",
        "primary-container": "#1b3b5a",
        "surface": "#faf9fc",
        "on-secondary-fixed": "#002117",
        "on-primary-fixed": "#001d35",
        "on-tertiary-fixed-variant": "#812629",
        "inverse-surface": "#2f3033",
        "error": "#ba1a1a",
        "on-primary-container": "#87a5ca",
        "on-tertiary-container": "#f77f7d",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f1f0f3",
        "outline-variant": "#c3c6ce",
        "secondary-fixed": "#b4efd7",
        "on-background": "#1a1c1e",
        "tertiary-fixed": "#ffdad8",
        "tertiary-fixed-dim": "#ffb3b0"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      }
    },
  },
  plugins: [],
}
